### ISSUE TITLE
MIT or AGPL3

### ISSUE THREAD

**Issue by iHiD** [exercism/pr-commenter-action#3]
@angelikatyborska Was there a specific reason you chose MIT for this over AGPL? If you explicitly want MIT then I'm fine with that (obviously, as it's your work), but if you don't have a preference, could we consider switching it to APGL3 before others contribute?

**Comment by angelikatyborska** [comment]
I always choose MIT because it's short, most popular on GitHub, and I don't really care about limiting what people can do with the code. I checked the Elixir repo and it uses MIT too, so I thought that's fine. I'm not very familiar with this whole topic, but it seems to me that life is easiest for everyone if OSS uses MIT libraries, right?

What's the reason to want APGL3 over MIT? Was there a situation that you encountered when having a MIT license caused problems?

**Comment by iHiD** [comment]
> What's the reason to want APGL3 over MIT? Was there a situation that you encountered when having a MIT license caused problems?

GPL (and its derivatives such as AGPL) means that if people use their code, they have to share any improvements they make. MIT means that anyone can take your work and change it and sell it without open sourcing any of the changes they've made.

So for something like the Analyzers and Representers, where I actively wouldn't want a a big-corp taking that work and hiding it in a proprietary system, we've made them all GPL.

So for this, the question is, if someone was to make a derivative work from this, would you want it to be Open Source and share improvements (AGPL) or would you be happy for someone to build it into their propriety systems.

> but it seems to me that life is easiest for everyone if OSS uses MIT libraries, right?

It would seem that way, but probably not. As MIT allows companies to just take your OSS work and build and sell close-sourced versions, and as GPL protects you from this, GPL is probably better if you purely want to help OSS, whereas MIT is best if you really don't care who uses your work and just want maximum reach. 

I have no particularly philosophical opinions - I think it tends to be quite situational.

**Comment by angelikatyborska** [comment]
> GPL is probably better if you purely want to help OSS, whereas MIT is best if you really don't care who uses your work and just want maximum reach.

Given this description of the difference, I would rather stay with MIT if that's not a problem.

**Comment by iHiD** [comment]
Sure! Thanks :)
